''' Minimal local type stub for the third-party `bitstring` package.

bitstring ships without inline type information, so its `read()` method is
typed as returning ``Union[int, float, str, Bits, bool, bytes, None]`` and
its `.hex` / `.bin` / `.u` / `.i` members aren't visible on that union at
all. In this codebase `read()` is always called with an integer bit count;
at runtime that always returns another `BitStream` (bitstring keeps the
concrete class on read/slice/concatenate, it does not narrow to the base
`Bits` type), so this stub models `BitStream` as a single self-contained
class and has every bit-producing operation return `BitStream`. That lets
type checkers infer `.u` / `.i` / `.read()` / `.pos` directly, so no
per-call `# type: ignore` is needed.

Only the members actually used in this codebase are declared.
'''

from typing import Iterator, overload

class BitStream:
    def __init__(self, auto: object = ..., length: int | None = ..., offset: int | None = ..., **kwargs: object) -> None: ...
    pos: int
    @property
    def u(self) -> int: ...
    @property
    def i(self) -> int: ...
    @property
    def b(self) -> str: ...
    @property
    def bin(self) -> str: ...
    @property
    def hex(self) -> str: ...
    @property
    def bytes(self) -> bytes: ...
    @overload
    def read(self, fmt: int) -> "BitStream": ...
    @overload
    def read(self, fmt: str) -> int: ...  # only 'u<n>' format strings are used in this codebase
    def any(self, value: int) -> bool: ...
    def all(self, value: int) -> bool: ...
    def tobytes(self) -> bytes: ...
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, key: int) -> bool: ...
    @overload
    def __getitem__(self, key: slice) -> "BitStream": ...
    def __add__(self, other: "BitStream") -> "BitStream": ...
    def __mul__(self, other: int) -> "BitStream": ...
    def __rmul__(self, other: int) -> "BitStream": ...
    def __iter__(self) -> Iterator[bool]: ...  # iterating yields one bool per bit

Bits = BitStream
ConstBitStream = BitStream
BitArray = BitStream
